# Generated by Django 4.2.7 on 2023-12-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="order",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.order"
            ),
        ),
    ]
